# General Settings
Prefix: "&8[&5&lAnti&d&lPlace&8] &7» "

# AntiPlace Settings
Blocked_Items:
    - Material.WHITE_CANDLE
    - Material.ORANGE_CANDLE
    - Material.MAGENTA_CANDLE
    - Material.LIGHT_BLUE_CANDLE
    - Material.YELLOW_CANDLE
    - Material.LIME_CANDLE
    - Material.PINK_CANDLE
    - Material.GRAY_CANDLE
    - Material.LIGHT_GRAY_CANDLE
    - Material.CYAN_CANDLE
    - Material.PURPLE_CANDLE
    - Material.BLUE_CANDLE
    - Material.BROWN_CANDLE
    - Material.GREEN_CANDLE
    - Material.RED_CANDLE
    - Material.BLACK_CANDLE